Repository OpenDevUFCG/poscomp, pull requests merged in 2019-10, with the labels that each got.

#31 Cria esqueleto da sidenav responsiva
  package.json
  src/components/app/App.css
  src/components/app/App.js
  src/components/app/content/PageContent.css
  src/components/app/content/PageContent.js
  src/components/app/content/header/PageHeader.css
  src/components/app/content/header/PageHeader.js
  src/components/app/sidenav/PageSideNav.css
  src/components/app/sidenav/PageSideNav.js
  src/components/content/main/MainField.css
  src/components/content/main/MainField.js
  src/components/header/PageHeader.css
  src/components/header/PageHeader.js
  src/components/sidenav/Backdrop.css
  src/components/sidenav/Backdrop.js
  src/components/sidenav/PageSideNav.css
  src/components/sidenav/PageSideNav.js
  src/components/toggleButton/ToggleButton.css
  src/components/toggleButton/ToggleButton.js
  src/index.css
  src/index.js
  src/pages/main/Main.css
  src/pages/main/Main.js
  src/routes.js
  yarn.lock
Labels: Aprimoramento, Frontend

#58 adiciona questões da prova de 2019 - matemática
  src/lib/provas/2019/16.json
  src/lib/provas/2019/17.json
  src/lib/provas/2019/19.json
  src/lib/provas/2019/20.json
Labels: Nova questão

#65 Adiciona parser para renderização de LaTex + plain text; Adiciona as questões 1, 2, 4, 5, 6 e 7 da prova de 2019
  package.json
  src/components/content/main/MainField.js
  src/components/render/KatexParser.js
  src/components/render/KatexRender.js
  src/lib/provas/2019/01.json
  src/lib/provas/2019/02.json
  src/lib/provas/2019/03.json
  src/lib/provas/2019/04.json
  src/lib/provas/2019/05.json
  src/lib/provas/2019/06.json
  src/lib/provas/2019/07.json
Labels: Aprimoramento, Configuração

#37 Adiciona enunciado e alternativas para questão 13
  src/lib/provas/2018/13.json
Labels: Nova questão

#59 adiciona questões da prova 2019 - fundamentos
  src/lib/provas/2018/11.json
  src/lib/provas/2018/34.json
  src/lib/provas/2018/35.json
  src/lib/provas/2019/11.json
  src/lib/provas/2019/13.json
  src/lib/provas/2019/23.json
  src/lib/provas/2019/24.json
  src/lib/provas/2019/26.json
  src/lib/provas/2019/29.json
  src/lib/provas/2019/30.json
  src/lib/provas/2019/32.json
  src/lib/provas/2019/36.json
  src/lib/provas/2019/37.json
Labels: Nova questão

#70 Prepara para novo design
  src/components/app/App.css
  src/components/content/main/MainField.js
  src/components/header/PageHeader.css
  src/components/header/PageHeader.js
Labels: Refatoramento
