Repository OpenDevUFCG/poscomp, pull requests merged in 2019-07, with the labels that each got.

#8 Adiciona arquivos padrão de um repositório
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
Labels: Aprimoramento, Configuração, Documentação

#11 Muda porta 8000 para 3000
  README.md
Labels: Bug, Documentação

#10 Adiciona estrutura dos arquivos JSON
  CONTRIBUTING.md
  README.md
  docs/AUTOR.md
  docs/QUESTAO.md
  lib/autores/autores.json
  lib/provas/2018/1.json
Labels: Aprimoramento, Documentação

#14 Move lib/ para src/lib/ para o seu conteudo ser acessado pelo react
  src/lib/autores/autores.json
  src/lib/provas/2018/1.json
Labels: Bug

#13 Renderizador de latex
  package.json
  public/index.html
  src/KatexRender.js
Labels: Aprimoramento, Frontend

#19 Adiciona checagem de ponto e virgula
  .eslintrc.json
Labels: Aprimoramento, Configuração

#18 Feature/cria estrutura básica da página
  public/index.html
  src/App.css
  src/App.js
  src/components/app/App.css
  src/components/app/App.js
  src/components/app/content/PageContent.css
  src/components/app/content/PageContent.js
  src/components/app/content/header/PageHeader.css
  src/components/app/content/header/PageHeader.js
  src/components/app/content/main/MainField.css
  src/components/app/content/main/MainField.js
  src/components/app/sidenav/PageSideNav.css
  src/components/app/sidenav/PageSideNav.js
  src/components/render/KatexRender.js
  src/index.css
  src/index.js
  yarn.lock
Labels: Aprimoramento, Frontend

#26 Adiciona questão 34 da prova de 2018 (e solução)
  src/lib/autores/autores.json
  src/lib/provas/2018/34.json
Labels: Aprimoramento, Nova questão

#21 adiciona questão + solução da questão 23 - 2018
  src/lib/provas/2018/23.json
Labels: Aprimoramento, Nova questão

#27 Adiciona questão 35 da prova de 2018 (e solução)
  src/lib/provas/2018/35.json
Labels: Aprimoramento, Nova questão
